#!/usr/bin/env python3.6
import asyncio
import logging

import aiorospy
import rospy
from actionlib.msg import TestAction, TestGoal, TestResult
from aiohttp import ClientSession, web
from std_msgs.msg import UInt64
from std_srvs.srv import SetString, SetStringResponse

# Quiet down warnings a bit so we can see the result more cleanly. Comment out to see what kinds of warnings we get.
logging.getLogger('aiohttp.access').setLevel(logging.WARNING)


def custom_exception_handler(loop, context):
    loop.default_exception_handler(context)
    exception = context.get('exception')
    print(exception)


class AiorospyTelephone:
    '''
    The Aiorospy Telephone is an exercise in single-thread concurrency to help illustrate the power of this paradigm.
    During the lifecycle of a single request, we have numerous pending tasks/coroutines for stateful I/O transactions.

    These include:
    - HTTP request
    - WebSocket connection
    - ROS Action
    - ROS Publisher/Subscriber
    - ROS Service call

    You'll notice that while there are underlying threads for some of the concurrent actions, the entire application
    flow is handled in a single thread in the event loop with numerous places where deadlocking would occur without
    concurrency. Part of the beauty of this model is that you can read and predict the control flow in a linear manner.

    Note that we jump between string and integer data to avoid having to create additional ROS message types for this
    example.

    Also note that we don't do much cleanup so a bunch of ROS stuff complains on shutdown. Typically one wouldn't have
    nodes connecting to themselves.
    '''

    def __init__(self):
        self.publisher = rospy.Publisher('hello_pub', UInt64, queue_size=1)
        self.subscriber = aiorospy.AsyncSubscriber('hello_pub', UInt64)
        self.action_server = aiorospy.AsyncSimpleActionServer('hello_action', TestAction, self.handle_action)
        self.action_client = aiorospy.AsyncSimpleActionClient('hello_action', TestAction)
        self.service = aiorospy.AsyncService('hello_world', SetString, self.handle_rosservice_call)
        self.service_proxy = aiorospy.AsyncServiceProxy('hello_world', SetString)
        self.http_server = web.Application()
        self.http_server.add_routes([
            web.get('/ws', self.handle_websocket_connection),
            web.get('/hello', self.handle_http_request)
        ])

        self.count = 0

        self.loop = asyncio.get_event_loop()
        self.loop.set_exception_handler(custom_exception_handler)

    async def send_goal(self):
        while True:
            print('Step 1: Create and dispatch an actionlib goal and await its completion.')
            goal = TestGoal()
            goal.goal = self.count
            result = await self.action_client.send_goal(goal)

            print('Step 10: print the actionlib goal result. Wow. That all sure was unnecessary.')
            print(f'The count is: {result.result}')
            await asyncio.sleep(5)
            self.count += 1

    async def handle_action(self, goal):
        print('Step 2: Handle the actionlib goal by making a ROS service call and await its completion.')
        response = await self.service_proxy.send(str(goal.goal))

        print('Step 9: Set the actionlib goal as succeeded, passing the service call response content as a result.')
        result = TestResult()
        result.result = int(response.message)
        # self.action_server.set_succeeded(result)
        self.loop.call_soon_threadsafe(self.action_server.set_succeeded, result)

    async def handle_rosservice_call(self, msg):
        async with ClientSession() as session:
            print('Step 3: Handle the ROS service call by making an HTTP request.')
            async with session.get(f'http://localhost:8080/hello?count={msg.data}') as response:
                print('Step 8: Await the HTTP response then respond to the ROS service call with the contents.')
                count = await response.text()
                await session.close()
                return SetStringResponse(True, count)

    async def handle_http_request(self, request):
        print('Step 4: Handle the HTTP request by establishing a WebSocket connection and sending a message.')
        value = request.rel_url.query['count']
        async with ClientSession() as session:
            async with session.ws_connect('http://localhost:8080/ws') as ws:
                await ws.send_str(str(value))

                print('Step 6: Wait for a ROS message to be published on the ROS topic.')
                msg = await self.subscriber.get()

                await session.close()
                print('Step 7: respond to the HTTP request with the contents of the ROS message.')
                return web.Response(text=str(msg.data))

    async def handle_websocket_connection(self, request):
        print('Step 5: Handle the WebSocket connection and message by publishing the data on the ROS topic.')
        ws = web.WebSocketResponse()
        await ws.prepare(request)
        async for msg in ws:
            self.publisher.publish(int(msg.data))

        return ws

    def start(self):
        # Prepare HTTP server.
        runner = web.AppRunner(self.http_server)
        self.loop.run_until_complete(runner.setup())
        site = web.TCPSite(runner)
        self.loop.run_until_complete(site.start())

        # Run infinite loops until shutdown.
        self.loop.run_until_complete(asyncio.gather(
            self.send_goal()
        ))


if __name__ == '__main__':
    rospy.init_node('aiorospy_telephone', disable_signals=True, log_level=rospy.ERROR)
    telephone = AiorospyTelephone()
    try:
        telephone.start()
    except KeyboardInterrupt:
        pass
    finally:
        rospy.signal_shutdown('Shutting down.')
